// ui/src/App.tsx
import { Component, createResource, createSignal, onMount, Show } from 'solid-js';
import axios from "axios";
import { FloatingBox } from './FloatingBox';
import { Login } from './Login';

const App: Component = () => {
    const [verify] = createResource(async () =>
        await axios.get("/api/verify", {
            withCredentials: true,
            params: {
                disable_redirect: true,
            },
        })
    );

    return (
        <Show when={(verify()?.status ?? -1) == 200}
            fallback={<Login />}
        >
            <FloatingBox>
                <h1>You're logged in</h1>
            </FloatingBox>
        </Show>
    );
};

export default App;

// ui/src/App.svelte
<script lang="ts">
    import axios from "axios";

    import { onMount } from "svelte";
    import FloatingBox from "./FloatingBox.svelte";
    import Login from "./Login.svelte";

    let is_logged_in = false;

    onMount(async () => {
        await axios.get("/api/verify", {
            withCredentials: true,
            params: {
                disable_redirect: true,
            },
        });
        is_logged_in = true;
    });
</script>

{#if is_logged_in}
    <FloatingBox>
        <h1>You're logged in</h1>
    </FloatingBox>
{:else}
    <Login />
{/if}
